version: '3.8'

services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: mdp
      MYSQL_DATABASE: gdclobby
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./api/db:/docker-entrypoint-initdb.d
  db-admin:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - '8080:8080'
  api:
    image: gdclobbyapi
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      NODE_ENV: production
    restart: always
    ports: # todo remove
      - '3000:3000'
