name: Rogue Wave Piercer - API

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  pull_request:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  deploy-back:
    name: Deploy API - ssh pull, build and run
    runs-on: ubuntu-latest
    steps:
      # TODO: Kill previous instance
      #- name: Kill
      #  uses: appleboy/ssh-action@master
      #  with:
      #      host: ${{secrets.HOST}}
      #      username: ${{ secrets.USERNAME }}
      #      key: ${{ secrets.KEY }}
      #      port: ${{ secrets.PORT }}
      #  script: |
      #    # TODO: cd to folder
      #    git pull
      - name: Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
        script: |
          # TODO: cd to folder
          git pull
      - name: Build and run
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
        script: |

      #   # TODO: How to keep running even after unlog. Screen for Windows ?
      #   screen -dmS "orwp-api"
      #   # TODO: cd to folder
      #   screen -S "orwp-api" -p 0 -X stuff " cd && ./start.cmd"
